# Generated by Django 2.0.1 on 2018-01-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memehub', '0002_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='published_date',
        ),
    ]
