# Generated by Django 2.0.1 on 2018-01-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memehub', '0003_remove_meme_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
