# Generated by Django 2.0.1 on 2018-01-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memehub', '0004_auto_20180109_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seenMemes',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
