# Generated by Django 2.0.1 on 2018-01-09 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memehub', '0005_profile_seenmemes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='seenMemes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='memehub.Meme'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
